# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrDNoTb--xTlQ3ZVSkMfZcM0fLypx9y7
"""

!pip install -q streamlit
!npm install -g localtunnel

!pip install pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# # Configuration de la page
# st.set_page_config(
#     page_title="WeatherAI - Station Météorologique Intelligente",
#     page_icon="🌤️",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # ==========================================
# # STYLES CSS PERSONNALISÉS (DESIGN MÉTÉO)
# # ==========================================
# st.markdown("""
#     <style>
#     /* Fond principal léger et typographie */
#     .stApp {
#         background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
#         font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
#     }
# 
#     /* Titre et Header principal */
#     .weather-header {
#         background: linear-gradient(90deg, #1e3c72 0%, #2a5298 100%);
#         padding: 25px;
#         border-radius: 18px;
#         color: white;
#         text-align: center;
#         box-shadow: 0px 8px 16px rgba(0,0,0,0.15);
#         margin-bottom: 25px;
#     }
# 
#     .weather-header h1 {
#         color: white !important;
#         font-size: 2.2rem;
#         font-weight: 700;
#         margin-bottom: 5px;
#     }
# 
#     .weather-header p {
#         font-size: 1.05rem;
#         opacity: 0.9;
#         margin-bottom: 0;
#     }
# 
#     /* Cartes de métriques/KPIs */
#     .metric-card {
#         background-color: rgba(255, 255, 255, 0.85);
#         backdrop-filter: blur(10px);
#         border-radius: 15px;
#         padding: 20px;
#         border: 1px solid rgba(255, 255, 255, 0.4);
#         box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
#         text-align: center;
#         margin-bottom: 15px;
#     }
# 
#     .metric-card h4 {
#         color: #555;
#         font-size: 0.95rem;
#         margin-bottom: 8px;
#         font-weight: 600;
#     }
# 
#     .metric-value {
#         font-size: 1.8rem;
#         font-weight: bold;
#         color: #1e3c72;
#     }
# 
#     /* Boîtes de résultat */
#     .result-card-rain {
#         background: linear-gradient(135deg, #ff4e50 0%, #f9d423 100%);
#         color: white;
#         padding: 25px;
#         border-radius: 18px;
#         box-shadow: 0 6px 18px rgba(255, 78, 80, 0.25);
#         text-align: center;
#     }
# 
#     .result-card-dry {
#         background: linear-gradient(135deg, #56ab2f 0%, #a8e063 100%);
#         color: white;
#         padding: 25px;
#         border-radius: 18px;
#         box-shadow: 0 6px 18px rgba(86, 171, 47, 0.25);
#         text-align: center;
#     }
# 
#     .result-card-amount {
#         background: linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%);
#         color: white;
#         padding: 25px;
#         border-radius: 18px;
#         box-shadow: 0 6px 18px rgba(33, 147, 176, 0.25);
#         text-align: center;
#     }
# 
#     /* Bouton principal */
#     .stButton>button {
#         background: linear-gradient(90deg, #1e3c72 0%, #2a5298 100%);
#         color: white !important;
#         border: none;
#         border-radius: 12px;
#         padding: 12px 28px;
#         font-size: 1.1rem;
#         font-weight: 600;
#         width: 100%;
#         box-shadow: 0 4px 12px rgba(30, 60, 114, 0.3);
#         transition: all 0.3s ease;
#     }
# 
#     .stButton>button:hover {
#         transform: translateY(-2px);
#         box-shadow: 0 6px 18px rgba(30, 60, 114, 0.4);
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# # ==========================================
# # HEADER DE L'APPLICATION
# # ==========================================
# st.markdown("""
#     <div class="weather-header">
#         <h1>🌤️ La Météo de SALMA </h1>
#         <p>Prédiction du risque et du volume de précipitation par Machine Learning</p>
#     </div>
# """, unsafe_allow_html=True)
# 
# # Chargement des ressources
# @st.cache_resource
# def load_resources():
#     model_clf = joblib.load('model_classification.pkl')
#     model_reg = joblib.load('model_regression.pkl')
#     scaler = joblib.load('scaler.pkl')
#     columns = joblib.load('model_columns.pkl')
#     return model_clf, model_reg, scaler, columns
# 
# try:
#     model_clf, model_reg, scaler, columns = load_resources()
# except Exception as e:
#     st.error(f"Erreur de chargement des modèles : {e}")
#     st.stop()
# 
# # ==========================================
# # BARRE LATÉRALE - PARAMÈTRES D'ENTRÉE
# # ==========================================
# st.sidebar.image("https://img.icons8.com/fluency/96/weather.png", width=70)
# st.sidebar.title("⚙️ Paramètres Météo")
# st.sidebar.markdown("Ajustez les observations du jour :")
# 
# def user_input_features():
#     st.sidebar.subheader("🌡️ Températures")
#     Temps_Min = st.sidebar.number_input("Minima (°C)", value=12.0, step=0.5)
#     Temp_Max = st.sidebar.number_input("Maxima (°C)", value=22.0, step=0.5)
# 
#     st.sidebar.subheader("💧 Humidité & Pluie")
#     Precipitation = st.sidebar.number_input("Pluie aujourd'hui (mm)", value=0.0, step=0.1)
#     Humidite_9h = st.sidebar.slider("Humidité Matin - 9h (%)", 0, 100, 65)
#     Humidite_15h = st.sidebar.slider("Humidité Après-midi - 15h (%)", 0, 100, 45)
# 
#     st.sidebar.subheader("📊 Pression")
#     Pression_15h = st.sidebar.number_input("Pression à 15h (hPa)", value=1015.0, step=0.5)
# 
#     data = pd.DataFrame(0, index=[0], columns=columns)
# 
#     mapping = {
#         'MinTemp': Temps_Min,
#         'MaxTemp': Temp_Max,
#         'Rainfall': Precipitation,
#         'Humidity9am': Humidite_9h,
#         'Humidity3pm': Humidite_15h,
#         'Pressure3pm': Pression_15h,
#     }
# 
#     for col, val in mapping.items():
#         if col in data.columns:
#             data[col] = val
# 
#     return data, Temps_Min, Temp_Max, Precipitation, Humidite_9h, Humidite_15h, Pression_15h
# 
# input_df, t_min, t_max, precip, hum_9, hum_15, press = user_input_features()
# 
# # ==========================================
# # TABLEAU DE BORD DES OBSERVATIONS
# # ==========================================
# st.subheader("📋 Les Observations du Jour")
# 
# col_kpi1, col_kpi2, col_kpi3, col_kpi4 = st.columns(4)
# 
# with col_kpi1:
#     st.markdown(f"""
#         <div class="metric-card">
#             <h4>🌡️ Températures</h4>
#             <div class="metric-value">{t_min}°C / {t_max}°C</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with col_kpi2:
#     st.markdown(f"""
#         <div class="metric-card">
#             <h4>💧 Humidité (15h)</h4>
#             <div class="metric-value">{hum_15}%</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with col_kpi3:
#     st.markdown(f"""
#         <div class="metric-card">
#             <h4>🌧️ Pluie Journée</h4>
#             <div class="metric-value">{precip} mm</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# with col_kpi4:
#     st.markdown(f"""
#         <div class="metric-card">
#             <h4>⏲️ Pression (15h)</h4>
#             <div class="metric-value">{press} hPa</div>
#         </div>
#     """, unsafe_allow_html=True)
# 
# st.write("")
# 
# # ==========================================
# # SECTION PRÉDICTION
# # ==========================================
# if st.button("🚀 Générer le Bulletin Météo pour Demain"):
# 
#     # Calculs de prédiction
#     pred_class = model_clf.predict(input_df)[0]
#     proba_class = model_clf.predict_proba(input_df)[0][1]
#     pred_amount = max(0.0, model_reg.predict(input_df)[0])
# 
#     st.markdown("---")
#     st.subheader("🎯 Prédictions Météorologiques pour Demain")
# 
#     col_res1, col_res2 = st.columns(2)
# 
#     with col_res1:
#         if pred_class == 1:
#             st.markdown(f"""
#                 <div class="result-card-rain">
#                     <h3>🌧️ Risque de Pluie Élevé</h3>
#                     <h1 style="font-size: 3rem; margin: 10px 0;">{proba_class*100:.1f}%</h1>
#                     <p style="font-size: 1.1rem;">Probabilité de précipitation demain</p>
#                 </div>
#             """, unsafe_allow_html=True)
#         else:
#             st.markdown(f"""
#                 <div class="result-card-dry">
#                     <h3>☀️ Temps Sec Prévu</h3>
#                     <h1 style="font-size: 3rem; margin: 10px 0;">{(1-proba_class)*100:.1f}%</h1>
#                     <p style="font-size: 1.1rem;">Probabilité de temps ensoleillé/sec</p>
#                 </div>
#             """, unsafe_allow_html=True)
# 
#     with col_res2:
#         st.markdown(f"""
#             <div class="result-card-amount">
#                 <h3>📏 Hauteur de Pluie Estimée</h3>
#                 <h1 style="font-size: 3rem; margin: 10px 0;">{pred_amount:.2f} mm</h1>
#                 <p style="font-size: 1.1rem;">Volume moyen prévu par le modèle de Régression</p>
#             </div>
#         """, unsafe_allow_html=True)

from pyngrok import ngrok

# Remplacez YOUR_AUTHTOKEN par le jeton copié sur ngrok.com
!ngrok config add-authtoken 3JppP1wG6jEgD4wdzntsejumVcc_3KWzHhy8TmwFSQKuGLGVa

# Lancer Streamlit en arrière-plan
!streamlit run app.py &> /dev/null &

# Ouvrir le tunnel Ngrok
public_url = ngrok.connect(8501)
print(f"🔗 Votre application est accessible ici : {public_url}")

!curl ipv4.icanhazip.com

!streamlit run app.py &> /dev/null & npx localtunnel --port 8501

