# -*- coding: utf-8 -*-
"""requirement.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNs5GFOlq5DmzaIGCMz2q67zdiWWusmO

# création de l'application

### Installer Streamlit et LocalTunnel dans Colab
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# scikit-learn
# joblib

